"""Add sequencing sessions, extension and retest support

Revision ID: ed7b2fe54c0a
Revises: 001
Create Date: 2026-03-21 13:31:57.716124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed7b2fe54c0a'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequencing_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('initial', 'retest', name='sessiontype'), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'extending', 'finalized', name='sessionstatus'), nullable=False),
    sa.Column('base_rounds', sa.Integer(), nullable=False),
    sa.Column('extension_batches', sa.Integer(), nullable=False),
    sa.Column('max_extension_batches', sa.Integer(), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('seed_movie_tmdb_id', sa.Integer(), nullable=True),
    sa.Column('reroll_excluded_tmdb_ids', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('season_label', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequencing_sessions_user_id'), 'sequencing_sessions', ['user_id'], unique=False)
    op.add_column('dna_profiles', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('dna_profiles', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('dna_profiles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('dna_profiles', 'genre_vector',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('dna_profiles', 'quadrant_scores',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('dna_profiles', 'hidden_traits',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('dna_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dna_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_dna_profiles_tag_vector'), table_name='dna_profiles', postgresql_ops={'tag_vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_dna_profiles_user_id'), table_name='dna_profiles')
    op.create_index(op.f('ix_dna_profiles_user_id'), 'dna_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_dna_profiles_session_id'), 'dna_profiles', ['session_id'], unique=True)
    op.create_foreign_key(None, 'dna_profiles', 'sequencing_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('groups', 'primary_tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('groups', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('groups', 'min_members_to_activate',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.alter_column('groups', 'member_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('matches', 'shared_tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('matches', 'shared_movies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('matches', 'ice_breakers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('matches', 'status',
               existing_type=postgresql.ENUM('discovered', 'invited', 'accepted', 'declined', name='matchstatus'),
               nullable=False,
               existing_server_default=sa.text("'discovered'::matchstatus"))
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('picks', sa.Column('session_id', sa.UUID(), nullable=True))
    op.alter_column('picks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_picks_session_id'), 'picks', ['session_id'], unique=False)
    op.create_foreign_key(None, 'picks', 'sequencing_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('active_session_id', sa.UUID(), nullable=True))
    op.alter_column('users', 'region',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'TW'::character varying"))
    op.alter_column('users', 'pure_taste_match',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'sequencing_status',
               existing_type=postgresql.ENUM('not_started', 'in_progress', 'completed', name='sequencingstatus'),
               nullable=False,
               existing_server_default=sa.text("'not_started'::sequencingstatus"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'users', 'sequencing_sessions', ['active_session_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'sequencing_status',
               existing_type=postgresql.ENUM('not_started', 'in_progress', 'completed', name='sequencingstatus'),
               nullable=True,
               existing_server_default=sa.text("'not_started'::sequencingstatus"))
    op.alter_column('users', 'pure_taste_match',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'region',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'TW'::character varying"))
    op.drop_column('users', 'active_session_id')
    op.drop_constraint(None, 'picks', type_='foreignkey')
    op.drop_index(op.f('ix_picks_session_id'), table_name='picks')
    op.alter_column('picks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('picks', 'session_id')
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('matches', 'status',
               existing_type=postgresql.ENUM('discovered', 'invited', 'accepted', 'declined', name='matchstatus'),
               nullable=True,
               existing_server_default=sa.text("'discovered'::matchstatus"))
    op.alter_column('matches', 'ice_breakers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('matches', 'shared_movies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('matches', 'shared_tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('groups', 'member_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('groups', 'min_members_to_activate',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('groups', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('groups', 'primary_tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(None, 'dna_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_dna_profiles_session_id'), table_name='dna_profiles')
    op.drop_index(op.f('ix_dna_profiles_user_id'), table_name='dna_profiles')
    op.create_index(op.f('ix_dna_profiles_user_id'), 'dna_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_dna_profiles_tag_vector'), 'dna_profiles', ['tag_vector'], unique=False, postgresql_ops={'tag_vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('dna_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dna_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dna_profiles', 'hidden_traits',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('dna_profiles', 'quadrant_scores',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('dna_profiles', 'genre_vector',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('dna_profiles', 'is_active')
    op.drop_column('dna_profiles', 'version')
    op.drop_column('dna_profiles', 'session_id')
    op.drop_index(op.f('ix_sequencing_sessions_user_id'), table_name='sequencing_sessions')
    op.drop_table('sequencing_sessions')
    # ### end Alembic commands ###
